GET http://localhost:8080/professional
# Endpoint: GET /professional
# Type of Response: JSON
#   professionalName: String
#   nameLink:
#       firstName: String
#       url:       String
#   primaryDescription: String
#   workDescription1: String
#   workDescription2: String
#   linkTitleText: String
#   linkedInLink:
#       text: String
#       link: String
#   githubLink:
#       text: String
#       link: String
#   base64Image: base64 encoded image